# Generated by Django 3.2.7 on 2021-11-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='videolink',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
